apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-2wf4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-2wf4@sha256:4316220d607797e8759b222c0a71ad70b24cfac641c898432adfae06fcf6b928
        name: my-nodejs
        resources: {}
status: {}
